---
- name: Add the postgres repo
  dnf:
    name: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    state: present

- name: Remove existing postgres
  command: dnf module disable postgresql -y

- name: Installing Postgres 11
  dnf:
    name:
      - postgresql11-server
      - postgresql11
      - pljava-11
      - python3-psycopg2
      - postgresql11-contrib
      - postgresql11-libs
      - java-1.8.0-openjdk 
      - java-1.8.0-openjdk-devel
    state: present

- name: Creating directory for postgres 
  file:
     name: "{{ postgres_localvolumemount }}"
     state: directory
     owner: postgres
     group: postgres
     mode: 0700

- name: Create directory
  file:
     name: /etc/systemd/system/postgresql-11.service.d/
     state: directory
     mode: 0770

- name: Changing the data path
  template:
     src: templates/override.conf.j2
     dest: /etc/systemd/system/postgresql-11.service.d/override.conf
     mode: 0644

- name: just force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: Check if PostgreSQL database is initialized.
  stat:
    path: "{{ postgres_localvolumemount }}/PG_VERSION"
  register: pgdata_dir_version

- name: Ensure PostgreSQL database is initialized.
  command: "/usr/pgsql-11/bin/initdb -D {{ postgres_localvolumemount }}"
  when: not pgdata_dir_version.stat.exists
  become: true
  become_user: "postgres"

- name: Enable external connection
  lineinfile:
        dest: "{{ postgres_localvolumemount }}/pg_hba.conf"
        line: 'host all all 0.0.0.0/0 md5'

- name: enable and start postgres
  systemd:
    name: postgresql-11
    state: started
    enabled: yes 
...